In [1]:
#ASE modules
from ase import Atoms
from ase.visualize import view
from ase.io import read,write
from ase.build import molecule
from ase.calculators.vasp import Vasp

#Python modules
import numpy as np
import matplotlib.pyplot as plt
from scipy.constants import physical_constants

In [9]:
def Calc_Encut(direct, en, atom):
    
    calc = Vasp(
            directory = direct,
            encut = en, #planewave cutoff
            xc = 'PBE', #exchange-correlation functional
            nbands = 8, #number of bands
            ismear = 1, #planewave smearing
            sigma = 0.01, #small smearing factor for a molecule
            kpts = [1,1,1],
            #ediff = 1e-6,
            atoms = atom,
            )
    
    return calc

In [29]:
d = 1.1

CO = Atoms('CO',
           positions = [ (0,0,0), (0,0, d) ],
           cell = [10,10,10],
           pbc = [1,1,1] #periodic boundary condition
          )

#CO.center()

view(CO)

<Popen: returncode: None args: ['/afs/.crc.nd.edu/x86_64_linux/p/python/3.10...>

In [30]:
calc_CO = Calc_Encut('./CO_lab3_3_01292023', 350, CO)
calc_CO.calculate(CO)

In [28]:
calc_CO.read()
CO = calc_CO.get_atoms()

print('Converged? ', calc_CO.converged)

ReadError: The file "CO_lab3_3_01292023/vasprun.xml" is incomplete, and no DFT data was available. This is likely due to an incomplete calculation.

In [21]:
#from calc object
print('Energy = {0} eV'.format(calc_CO.get_potential_energy()))
print('Forces (eV/Ang.):')
print(calc_CO.get_forces())


Energy = -13.13971275 eV
Forces (eV/Ang.):
[[ -0.           0.         -27.70914245]
 [  0.          -0.          27.70914245]]


In [22]:
#from atoms object
print('Energy = {0} eV'.format(CO.get_potential_energy()))
print('Forces (eV/Ang.):')
print(CO.get_forces())

Energy = -13.13971275 eV
Forces (eV/Ang.):
[[ -0.           0.         -27.70914245]
 [  0.          -0.          27.70914245]]


In [23]:
#print status of calculation
print(calc_CO)